name: 'Setup Rsync'
description: 'Github actions to setup Rsync (all os supported) 🔄'

inputs:
  ssh_key:
    description: SSH KEY to setup
    required: false

outputs:
  ssh_key_path:
    description: "SSH KEY path"
    value: ${{ steps.setup_ssh_key.outputs.ssh_key_path }}

runs:
  using: "composite"
  steps:
    - name: Check OS
      id: ostype
      run: |
        if [[ $OSTYPE == 'msys'* ]]; then
          echo "Windows detected"
          echo "ostype=windows" >> $GITHUB_OUTPUT
        elif [[ $OSTYPE == 'darwin'* ]]; then 
          echo "MacOS detected"
          echo "ostype=macos" >> $GITHUB_OUTPUT
        else
          echo "Linux detected"
          echo "ostype=linux" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Install Rsync Windows
      if: steps.ostype.outputs.ostype == 'windows'
      run: |
        choco install --no-progress rsync
      shell: pwsh
    
    - name: Install Rsync MacOS
      if: steps.ostype.outputs.ostype == 'macos'
      run: |
        echo "macos runner detected"
        brew install rsync
        echo "rsync installed on macos runner"
      shell: bash
    
    - name: Install Rsync Ubuntu
      if: steps.ostype.outputs.ostype == 'linux'
      run: |
        echo "ubuntu runner detected"
        sudo apt-get -qq update
        sudo apt-get install rsync
        echo "rsync installed on ubuntu runner"
      shell: bash

    - name: Check Rsync version
      run: rsync --version
      shell: bash

    - name: Setup SSH KEY
      id: setup_ssh_key
      run: |
        if [ -z "${{ inputs.ssh_key }}" ]; then
          echo "INFO: No SSH KEY provided."
        elif [ ! -v CYGWIN ]; then
          temp_path="${{ runner.temp }}"
          temp_path="${temp_path//\\//}"
          echo "${{ inputs.ssh_key }}" > "${temp_path}/sshkey"
          chmod 600 "${{runner.temp}}/sshkey"
          echo "ssh_key_path=${{runner.temp}}/sshkey" >> $GITHUB_OUTPUT
        else
          echo "This action is not supported on CYGWIN Bash"
        fi
      shell: bash

branding:
  icon: arrow-right-circle
  color: blue