name: 'Setup Rsync'
description: 'Github actions to setup Rsync (all os supported) 🔄'

runs:
  using: "composite"
  steps:
    - name: Install Rsync Windows
      if: {{ $OSTYPE == 'msys'* }}
      uses: egor-tensin/setup-cygwin@v4
      with:
        packages: rsync
    
    - name: Install Rsync MacOS
      if: {{ $OSTYPE == 'darwin'* }}
      run: |
        echo "macos runner detected"
        brew install rsync
        echo "rsync installed on macos runner"
      shell: bash
    
    - name: Install Rsync Ubuntu
      if: {{ $OSTYPE == 'linux'* }}
      run: |
        echo "ubuntu runner detected"
        sudo apt-get install rsync
        echo "rsync installed on ubuntu runner"
      shell: bash

    - name: Check Rsync version
      run: rsync --version
      shell: bash

branding:
  icon: arrow-right-circle
  color: blue