name: 'Setup Rsync'
description: 'Github actions to setup Rsync (all os supported) 🔄'

runs:
  using: "composite"
  steps:
    - name:
      run: |
        if [[ $OSTYPE == 'msys'* ]]; then
          echo "windows runner detected"
          zstd -d ..\rsync-3.2.3-1-x86_64.pkg.tar.zst
          mv rsync-3.2.3-1-x86_64.pkg\usr\bin\ C:\Program Files\Git\usr\bin\
          zstd -d ..\libzstd-1.4.7-1-x86_64.pkg.tar.xz
          zstd -d ..\libxxhash-0.8.0-1-x86_64.pkg.tar.zst
          echo "rsync installed on windows runner"
        elif [[ $OSTYPE == 'darwin'* ]]; then 
          echo "macos runner detected"
          brew install rsync
          echo "rsync installed on macos runner"
        else
          echo "ubuntu runner detected"
          sudo apt-get install rsync
          echo "rsync installed on ubuntu runner"
        fi
        rsync --version
      shell: bash