name: 'Setup Rsync'
description: 'Github actions to setup Rsync (all os supported)'

runs:
  using: "composite"
  steps:
    - name:
      run: |
        echo $OSTYPE
        if [[ $OSTYPE == 'win'* ]]; then
          echo "windows"
          wsl --install
        elif [[ $OSTYPE == 'darwin'* ]]; then 
          echo "macos"
          brew install rsync
        else
          echo "linux"
          sudo apt-get install rsync
        fi
        rsync -V
      shell: bash