name: 'Setup Rsync'
description: 'Github actions to setup Rsync (all os supported)'

runs:
  using: "composite"
  steps:
    - name:
      run: |
        echo $OSTYPE
        if [[ $OSTYPE == 'msys'* ]]; then
          echo "windows runner detected"
          wsl --install
        elif [[ $OSTYPE == 'darwin'* ]]; then 
          echo "macos runner detected"
          brew install rsync
        else
          echo "ubuntu runner detected"
          sudo apt-get install rsync
        fi
        rsync --version
      shell: bash