name: Action test

on:
  push:
  workflow_dispatch:

jobs:
  rsyncversion:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name:  ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: ''
      - name: Setup rsync NOT Windows
        if: ${{ runner.os != "Windows" }}
        uses: ./
      - name: Setup rsync Windows
        if: ${{ runner.os == "Windows" }}
        uses: '.\'
      - run: rsync --version
