name: publish-action
on:
  release:
    types: released
  workflow_dispatch:
    inputs:
      tag_name:
        description: vX.Y.Z
        required: true
jobs:
  update_tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/publish-action@v0.3.0
        with:
          source-tag: ${{ github.event.inputs.tag_name || github.event.release.tag_name }}
